[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --chdir backend --worker-class gthread --workers 1 --threads 4 --timeout 120 --preload app:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
